config/routes.rb
Borker::Application.routes.draw do

  root 'borks#index'

  namespace :api do
    resources :users, only: [:index]
    post 'authenticate' => 'users#authenticate'
    post 'add_token' => 'users#add_token'
    get 'user_borks' => 'users#user_borks'
    get 'user_id' => 'users#user_id'
    get 'favorites' => 'users#favorites'
    resources :borks, only: [:index, :create]
    delete 'borks' => 'borks#destroy'
    post 'undo_delete' => 'borks#undo_delete'
    resources :notifications, only: [:index]
    post 'favorites' => 'favorites#create'
    delete 'favorites' => 'favorites#destroy'
    get 'favorited' => 'favorites#favorited'
    get 'bork_favorites' => 'borks#bork_favorites'
  end

  get 'sessions/new', as: 'login'
  get 'sessions/create'
  get 'sessions/destroy', as: 'logout'

  get 'signup' => 'users#new', as: 'signup'
  get 'users/:id/favorites' => 'users#favorites', as: 'favorites'
  get 'borks/:id/favorite' => 'favorites#create', as: 'favorite'
  get 'borks/:id/unfavorite' => 'favorites#destroy', as: 'unfavorite'

  get 'jamesify' => 'borks#jamesify', as: 'jamesify_bork'
  get 'borks_for_app.json' => 'borks#borks_for_app'
  get 'random' => 'borks#random'

  resources :sessions
  resources :users
  resources :borks
  resources :notifications

end

app/models/bork.rb
class Bork < ActiveRecord::Base
  acts_as_paranoid
  validates :content, :length => { :maximum => 160 }, :presence => true

  belongs_to :user

  has_many :notifications, dependent: :destroy
  has_many :favorites, dependent: :destroy

  mount_uploader :attachment, AvatarUploader
end

app/controllers/api/borks_controller.rb
class Api::BorksController < ApiController
  before_filter :require_valid_bork_id, only: [:destroy, :undo_delete]
  before_filter :require_valid_username, only: [:create, :destroy, :undo_delete]
  before_filter :require_limit, only: [:index]
  before_filter :require_content, only: [:create]
  before_filter :require_date, only: [:index]

  def index
    if params[:older_than].present?
      older_than = Time.parse(params[:older_than])
      render json: Bork.all.limit(params[:limit]).where('created_at < ?', older_than).order('created_at DESC')
    else
      since = Time.parse(params[:since])
      render json: Bork.all.limit(params[:limit]).where('created_at > ?', since).order('created_at DESC')
    end
  end

  def create
    unless too_long?
      Bork.create(content: params[:content], user_id: User.find_by(username: params[:username]).id)
      head :ok
    else
      render json: "Bork content too long", status: 422
    end
  end

  def destroy
    @bork = Bork.find(params[:bork_id])
    if owns_bork?
      @bork.destroy
      head :ok
    else
      render json: "That's not your bork!", status: 422
    end
  end

  def undo_delete
    @bork = Bork.with_deleted.find(params[:bork_id])
    if owns_bork?
      @bork.deleted_at = nil
      head :ok
    else
      render json: "That's not your bork!", status: 422
    end
  end

  def too_long?
    params[:content].length > 160
  end

  def owns_bork?
    @bork.user.username == params[:username]
  end

  def bork_favorites
    render json: Favorite.where(bork_id: params[:bork_id])
  end
end

app/controllers/borks_controller.rb
class BorksController < ApplicationController
  include ActionView::Helpers::TextHelper

  def index
    @borks = Bork.all.order('created_at DESC').page(params[:page]).per(50)
    @bork = Bork.new
  end

  def random
    @bork = Bork.order("RANDOM()").first
  end

  def new
    @bork = Bork.new
  end

  def jamesify
    text = params[:bork].downcase

    (text.length/75).round.times do
      text[rand(text.length)] = ('a'..'z').to_a.push('').sample
    end
    text[rand(text.length)] = ''
    text_array = text.downcase.split(' ')

    (text_array.length/1.5).round.times do
      text_array.sample.squeeze!
    end

    (text_array.length/4).round.times do
      text_array.sample.capitalize!
    end

    @james_bork = text_array.join(' ')
  end

  def create
    @bork = Bork.new(bork_params)
    @bork.user = current_user
    @bork.content = strip_tags(@bork.content)

    if @bork.save
      redirect_to root_url, notice: "Thanks for Borking!"
    else
      render "new"
    end
  end


  def show
    @bork = Bork.find(params[:id])
  end

  def destroy
    Bork.find(params[:id]).destroy
    redirect_to :back
  end

  private

  def bork_params
    params.require(:bork).permit(:content, :attachment)
  end
end

app/helpers/borks_helper.rb
module BorksHelper
  REGEXP = /((@)[\w\-]+|(#)[\w\-]+)/
  def linkify_keywords(bork)
    if bork
      return bork.content.gsub(REGEXP) do |match|
        case $~.captures.compact[1]
          when "@" then
            if user = User.find_by(username: match[1..-1])
              author = Bork.find_by(content: bork.content).user
              Notification.find_or_create_by(author: author, user: user, action: "mention", bork: bork)
              "<a href='/users/#{user.id}'>#{match}</a>"
            else
              match
            end
          when "#" then "<a href='#'>#{match}</a>"
        end
      end
    end
  end
end

app/views/borks/_bork.html.slim
.bork.row
  .small-2.columns.avi
    .avatar= image_tag bork.user.avatar.url(:thumb), size: "48x48"
  .small-8.columns.content
    .user= link_to "@"+bork.user.username, user_path(bork.user.id)
    .text class="#{'no-wrap' if bork.id == 998}"
      = auto_link linkify_keywords(bork)
    - if bork.attachment?
      = link_to "Show Attachment", "#", class: "show_attachment"
      .attachment.hide= link_to (image_tag bork.attachment.url), bork.attachment.url
  .small-2.columns.when
    .time= timeago_tag bork.created_at, nojs: true, limit: 10.days.ago
  .actions
    - if current_user.favorited?(bork)
      = link_to "Unfavorite", unfavorite_path(bork.id), remote: true
    - else
      = link_to "Favorite", favorite_path(bork.id), remote: true
    - if bork.user == current_user
      = link_to "Delete", bork_path(bork.id), method: :delete, data: { confirm: "You sure you wanna unbork it?"}

app/views/borks/_form.html.slim
= form_for @bork do |f|
  .row
    .small-12.columns
      .charactercount.right
      = f.text_area :content, placeholder: "Compose a new Bork..."
  .row.bork-action.hide
    .small-8.columns
      = link_to "Jamesify", "#", remote: true, id: "jamesify"
      .attachment
        = f.file_field :attachment
    .small-4.columns
      = f.submit "Bork", class: "button small right"

javascript:
  var path = "#{jamesify_bork_path}"
coffee:
  $ ->
    $("#jamesify").click (e) ->
      e.preventDefault()
      $.ajax
        url: path
        data: {bork: $('#bork_content').val()}

    $("#bork_content").keyup (e) ->
      $(".charactercount").removeClass("too-long");
      if this.value.length > 0
        $(".charactercount").html(this.value.length+"/160");
        if this.value.length > 160
          $(".charactercount").addClass("too-long");
      else
        $(".charactercount").html("");

app/views/borks/index.html.slim
.row
  .new-bork.content-area
    .user= link_to user_path(current_user.id) do
      .small-2.columns.avatar-preview
        = image_tag current_user.avatar.url(:thumb)
      .small-10.columns.username
        h6= current_user.username
        p View my profile page
    hr
    .info= link_to user_path(current_user.id) do
      .small-2.columns
        h6= current_user.borks.count
        p borks
    hr
    = render 'borks/form'
  .bork-container.index-borks.content-area
    h3 Borks
    hr
    .borks
      = render @borks
    .pagination
      = paginate @borks

app/views/borks/new.html.slim
= render 'form'

app/views/borks/random.html.slim
h5.bork style="background: white;"= "#{@bork.user.username}: #{@bork.content}"

app/views/borks/show.html.slim
= render @bork