config/routes.rb
Borker::Application.routes.draw do

  root 'borks#index'

  namespace :api do
    resources :users, only: [:index]
    post 'authenticate' => 'users#authenticate'
    post 'add_token' => 'users#add_token'
    get 'user_borks' => 'users#user_borks'
    get 'user_id' => 'users#user_id'
    get 'favorites' => 'users#favorites'
    resources :borks, only: [:index, :create]
    delete 'borks' => 'borks#destroy'
    post 'undo_delete' => 'borks#undo_delete'
    resources :notifications, only: [:index]
    post 'favorites' => 'favorites#create'
    delete 'favorites' => 'favorites#destroy'
    get 'favorited' => 'favorites#favorited'
    get 'bork_favorites' => 'borks#bork_favorites'
  end

  get 'sessions/new', as: 'login'
  get 'sessions/create'
  get 'sessions/destroy', as: 'logout'

  get 'signup' => 'users#new', as: 'signup'
  get 'users/:id/favorites' => 'users#favorites', as: 'favorites'
  get 'borks/:id/favorite' => 'favorites#create', as: 'favorite'
  get 'borks/:id/unfavorite' => 'favorites#destroy', as: 'unfavorite'

  get 'jamesify' => 'borks#jamesify', as: 'jamesify_bork'
  get 'borks_for_app.json' => 'borks#borks_for_app'
  get 'random' => 'borks#random'

  resources :sessions
  resources :users
  resources :borks
  resources :notifications

end

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    title= content_for?(:title) ? yield(:title) : "Borker"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "vendor/custom.modernizr"
    = csrf_meta_tags
    = javascript_include_tag "application"
  body
    .nav
      .row
        h2.title= link_to "Borker", root_url
        .right
          h6= link_to "Borkers", users_path
          - if current_user
            h6= link_to "Notifications (#{current_user.notifications.where("notifications.read IS NULL OR notifications.read IS FALSE").count})", notifications_path
            h6= link_to current_user.username.capitalize, user_path(current_user.id)
            h6= link_to "Log Out", logout_path
          - else
            h6= link_to "Log In", login_path

    - if flash[:alert]
      .alert-box.radius.alert data-alert=""
        = flash[:alert]
        a.close href="#" &times;
    = yield